name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v2
        with:
          java-version: 17
      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug --no-daemon

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: chmod +x gradlew
      - uses: android-actions/setup-android@v2
        with:
          java-version: 17
      - run: ./gradlew testDebugUnitTest --no-daemon

  ui-tests:
    runs-on: ubuntu-latest
    needs: [build, unit-tests]
    strategy:
      matrix:
        avd: [ "pixel_6a_api_33", "pixel_4_api_33" ]  # Параллельные эмуляторы
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: chmod +x gradlew
      - uses: android-actions/setup-android@v2
        with:
          java-version: 17

      - name: Run UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          avd: ${{ matrix.avd }}
          emulator-options: >-
            -no-window
            -no-audio
            -no-boot-anim
            -gpu swiftshader_indirect
            -no-snapshot-load
            -no-snapshot-save
          script: ./gradlew connectedDebugAndroidTest --no-daemon
