name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Настройка Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk: 25.2.9519653

      # Кэш Gradle для ускорения сборки
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # Сборка Debug
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Юнит-тесты
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

      # Настройка эмулятора и запуск инструментальных тестов
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest --no-daemon
