name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверяем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # Настройка Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Настройка Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          java-version: 17
          # без указания api-level/build-tools/ndk, чтобы не ругался

      # Делаем gradlew исполняемым
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Сборка Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
