name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Настройка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Настройка Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          java-version: 17

      # Делаем gradlew исполняемым
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Сборка Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Запуск unit-тестов
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon

      # Установка Android Emulator
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest --no-daemon
